//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("TMProxy", ClrNamespace="TMProxy")]

namespace TMProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataLocation", Namespace="TMProxy")]
    public partial struct DataLocation : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TMProxy.DMLocation _dmLocationField;
        
        private int _indexField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TMProxy.DMLocation _dmLocation
        {
            get
            {
                return this._dmLocationField;
            }
            set
            {
                this._dmLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _index
        {
            get
            {
                return this._indexField;
            }
            set
            {
                this._indexField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMLocation", Namespace="TMProxy")]
    public partial struct DMLocation : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EndpointNameField;
        
        private string RemoteAddressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndpointName
        {
            get
            {
                return this.EndpointNameField;
            }
            set
            {
                this.EndpointNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemoteAddress
        {
            get
            {
                return this.RemoteAddressField;
            }
            set
            {
                this.RemoteAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Change", Namespace="TMProxy")]
    public partial class Change : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsWriteField;
        
        private TMProxy.DataLocation LocationField;
        
        private byte ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWrite
        {
            get
            {
                return this.IsWriteField;
            }
            set
            {
                this.IsWriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TMProxy.DataLocation Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}
namespace DistributedConcurrency
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vote", Namespace="http://schemas.datacontract.org/2004/07/DistributedConcurrency")]
    public enum Vote : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abort = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commit = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataManager")]
public interface IDataManager
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/Read", ReplyAction="http://tempuri.org/IDataManager/ReadResponse")]
    byte Read(TMProxy.DataLocation location);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/Write", ReplyAction="http://tempuri.org/IDataManager/WriteResponse")]
    void Write(TMProxy.DataLocation location, byte value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/Begin", ReplyAction="http://tempuri.org/IDataManager/BeginResponse")]
    void Begin();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/End", ReplyAction="http://tempuri.org/IDataManager/EndResponse")]
    void End();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/Abort", ReplyAction="http://tempuri.org/IDataManager/AbortResponse")]
    void Abort();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/Restart", ReplyAction="http://tempuri.org/IDataManager/RestartResponse")]
    void Restart();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/StageChange", ReplyAction="http://tempuri.org/IDataManager/StageChangeResponse")]
    byte StageChange(TMProxy.Change change);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataManager/EndStagingPhase", ReplyAction="http://tempuri.org/IDataManager/EndStagingPhaseResponse")]
    DistributedConcurrency.Vote EndStagingPhase();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataManagerChannel : IDataManager, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataManagerClient : System.ServiceModel.ClientBase<IDataManager>, IDataManager
{
    
    public DataManagerClient()
    {
    }
    
    public DataManagerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataManagerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public byte Read(TMProxy.DataLocation location)
    {
        return base.Channel.Read(location);
    }
    
    public void Write(TMProxy.DataLocation location, byte value)
    {
        base.Channel.Write(location, value);
    }
    
    public void Begin()
    {
        base.Channel.Begin();
    }
    
    public void End()
    {
        base.Channel.End();
    }
    
    public void Abort()
    {
        base.Channel.Abort();
    }
    
    public void Restart()
    {
        base.Channel.Restart();
    }
    
    public byte StageChange(TMProxy.Change change)
    {
        return base.Channel.StageChange(change);
    }
    
    public DistributedConcurrency.Vote EndStagingPhase()
    {
        return base.Channel.EndStagingPhase();
    }
}
